/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module passOrFail_8 (
    input [1:0] checker,
    input [1:0] circuit,
    output reg [3:0] out
  );
  
  
  
  always @* begin
    if (checker == circuit) begin
      out = 4'h8;
    end else begin
      out = 4'h9;
    end
  end
endmodule
