/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module choose_lut_12 (
    input [3:0] in,
    output reg [1:0] out
  );
  
  
  
  wire [2-1:0] M_onebfa_lut_out;
  reg [4-1:0] M_onebfa_lut_in;
  onebfa_lut_16 onebfa_lut (
    .in(M_onebfa_lut_in),
    .out(M_onebfa_lut_out)
  );
  
  wire [2-1:0] M_fake_lut_out;
  reg [4-1:0] M_fake_lut_in;
  fake_lut_17 fake_lut (
    .in(M_fake_lut_in),
    .out(M_fake_lut_out)
  );
  
  integer L_table;
  
  always @* begin
    M_onebfa_lut_in = in;
    M_fake_lut_in = in;
    L_table = 1'h1;
    
    case (L_table)
      1'h0: begin
        out = M_onebfa_lut_out;
      end
      1'h1: begin
        out = M_fake_lut_out;
      end
      default: begin
        out = M_onebfa_lut_out;
      end
    endcase
  end
endmodule
