/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fake_lut_17 (
    input [3:0] in,
    output reg [1:0] out
  );
  
  
  
  always @* begin
    
    case (in)
      4'h0: begin
        out = 2'h1;
      end
      4'h1: begin
        out = 2'h3;
      end
      4'h2: begin
        out = 2'h0;
      end
      4'h4: begin
        out = 2'h1;
      end
      4'h3: begin
        out = 2'h3;
      end
      4'h5: begin
        out = 2'h2;
      end
      4'h6: begin
        out = 2'h0;
      end
      4'h7: begin
        out = 2'h3;
      end
      default: begin
        out = 2'h0;
      end
    endcase
  end
endmodule
